Types and variables
NiksPetersons/c-sharp-syllabus pull request #1
Opened 2022-07-27 19:39 UTC by NiksPetersons

2022-07-27 20:31 UTC, ausmoons requested changes

2022-07-27 20:31 UTC, ausmoons commented on TypesAndVariables/Casting/Program.cs
> +            int a = 1;
Dotos lielumus te nevar mainī. Jākonvertē

2022-07-27 20:31 UTC, ausmoons commented on TypesAndVariables/Exercise6/Program.cs
> +
Vajadzētu tukšu rindu pēc }, nevis pirms

2022-07-29 18:07 UTC, EdgarsSalmins commented on TypesAndVariables/Exercise6/Program.cs
> +
all good.. izlabots.

2022-07-29 18:07 UTC, EdgarsSalmins approved these changes

2022-07-29 18:38 UTC, merged