Arithmetic
NiksPetersons/c-sharp-syllabus pull request #2
Opened 2022-07-29 14:03 UTC by NiksPetersons

Arithmetic mape

2022-07-29 19:16 UTC, NiksPetersons commented
Neesmu drošs kā man tie pirmie commitu šajā branchā gadījās. Man tas jālabo?

2022-07-29 20:23 UTC, ausmoons requested changes

2022-07-29 20:23 UTC, ausmoons commented on Arithmetic/CalculateArea/Program.cs
> +            } else if (userChoice == 2)
else if jaunā rindā

2022-07-29 20:23 UTC, ausmoons commented on Arithmetic/CalculateArea/Program.cs
> +            while (userChoice >5 || userChoice < 1)
Kur būs 5?

2022-07-29 20:23 UTC, ausmoons commented on Arithmetic/Exercise11/Program.cs
> +            bool primeCheck = PrimeCheck(number / sumOfDigits);
tukša rinda pēc }

2022-07-29 20:23 UTC, ausmoons commented on Arithmetic/Exercise2/Program.cs
> +            Console.WriteLine("Hello World!");
?

2022-07-29 20:23 UTC, ausmoons commented on Arithmetic/Exercise8/Program.cs
> +            } else if (weeklyHours > maximumWeeklyHours)
Jaunā rindā

2022-07-30 12:42 UTC, NiksPetersons commented
TypesAndVariables failus var ignorēt, netīšām šo branch bāzēju uz iepriekšējā, nevis main. Types un variables approve jau dabūts

2022-07-30 20:08 UTC, ausmoons commented on Arithmetic/CalculateArea/Geometry.cs
>              throw new NotImplementedException();
Lieks

2022-07-30 20:14 UTC, ausmoons requested changes

2022-07-30 20:14 UTC, ausmoons commented on Arithmetic/CozaLozaWoza/Program.cs
> +                if (i % 11 == 0)
Pirms jauna if vajag tukšu rindu

2022-07-30 20:14 UTC, ausmoons commented on Arithmetic/Exercise9/Program.cs
> +            } else if (calculatingBMI > overweightBMI)
else if jaunā rindā

2022-07-30 20:51 UTC, ausmoons approved these changes

2022-07-30 21:23 UTC, merged