Polymorphism
NiksPetersons/c-sharp-syllabus pull request #8
Opened 2022-08-19 14:13 UTC by NiksPetersons

Polymorphism mape

2022-08-20 08:19 UTC, ausmoons requested changes

2022-08-20 08:19 UTC, ausmoons commented on Polymorphism/AdApp/Hoarding.cs
> +            this._rate = rate;
![image](https://user-images.githubusercontent.com/53189160/185735848-193b199c-4704-4559-b662-44e8a923633c.png)
this. ir lieks

2022-08-20 08:19 UTC, ausmoons commented on Polymorphism/AdApp/Poster.cs
> +            double cost = base.Cost() + _copies * _costPerCopy;
var uzreiz return, jo cost netiek citur izmantots

2022-08-20 08:19 UTC, ausmoons commented on Polymorphism/DragRace/Bmw.cs
> +}
Te kkas nav ok ar tab

2022-08-20 08:19 UTC, ausmoons commented on Polymorphism/Firm/Commission.cs
> +            eAddress, ePhone, socSecNumber, rate)
: base(eName,  eAddress, ePhone, socSecNumber, rate)

2022-08-20 08:19 UTC, ausmoons commented on Polymorphism/Firm/Commission.cs
> +            eAddress, ePhone, socSecNumber, rate)
Visu jaunā rindā

2022-08-20 08:19 UTC, ausmoons commented on Polymorphism/Hierarchy/Mammal.cs
> +            this.LivingRegion = livingRegion;
Kāpēc tu liec this.?

2022-08-20 08:19 UTC, ausmoons commented on Polymorphism/VendingMachine/VendingMachine.cs
> +            Products = new Product[slotAmount];
Parasti šeit iekšā visi ir private

2022-08-20 08:19 UTC, ausmoons commented on Polymorphism/VendingMachine/VendingMachine.cs
> +        public bool UpdateProduct(int productNumber, string name, Money? price, int amount)
Uz kādu jautājumu atbild  UpdateProduct?

2022-08-20 08:19 UTC, ausmoons commented on Polymorphism/VendingMachine/VendingMachine.cs
> +            if (Products[index-1].Available > 0 && Products[index-1].Name != null && index-1 < Products.Length)
return uzreiz

2022-08-20 08:19 UTC, ausmoons commented on Polymorphism/VendingMachine/VendingMachine.cs
> +            int totalCents = money.Cents + money.Euros * 100;
return var uzreiz

2022-08-20 10:58 UTC, NiksPetersons commented on Polymorphism/VendingMachine/VendingMachine.cs
> +        public bool UpdateProduct(int productNumber, string name, Money? price, int amount)
Tas jau bija dots un pēc uzdevuma nosacījumiem mainīt nedrīkst

2022-08-20 11:06 UTC, NiksPetersons commented on Polymorphism/VendingMachine/VendingMachine.cs
> +            Products = new Product[slotAmount];
Īsti nesapratu, visiem mainīgajiem, kurus inicializē konstruktorā jābūt private? Ja interfeisā ir dots public tad ar "public Var => private _var" pārtaisīt?

2022-08-20 11:34 UTC, NiksPetersons commented on Polymorphism/Firm/Commission.cs
> +            eAddress, ePhone, socSecNumber, rate)
Tas ir tikai līnijas garuma dēļ, vai labāk vienmēr base parametrus jaunā rindā likt?

2022-08-21 17:43 UTC, ausmoons commented on Polymorphism/VendingMachine/VendingMachine.cs
> +            Products = new Product[slotAmount];
Jap, parasti tā pārtaisa

2022-08-21 17:45 UTC, ausmoons commented on Polymorphism/Firm/Commission.cs
> +            eAddress, ePhone, socSecNumber, rate)
skatās pēc situācijas. Šajā gadījumā viss base ieiet vienā līnijā, tad to liek kopā jaunā līnijā. Ja neieietu vienā līnijā, tad citi dala pat pa vārdam. Bet nav smuki, ka puse līnijas ir iepriekšējā rindā, ja viss var ieiet vienā jaunā.

2022-08-21 17:46 UTC, ausmoons requested changes

2022-08-21 17:46 UTC, ausmoons commented on Polymorphism/VendingMachine/VendingMachine.cs
> +        private bool _hasProducts { get; set; }
private nav set

2022-08-23 19:10 UTC, ausmoons approved these changes

2022-08-23 19:58 UTC, merged